[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[template.environment]
  VITE_SUPABASE_URL = "Supabase Project URL"
  VITE_SUPABASE_ANON_KEY = "Supabase Anon Key"
  VITE_PAYPAL_CLIENT_ID = "PayPal Client ID"
  VITE_SERPAPI_KEY = "SerpAPI Key"
  VITE_RESEND_API_KEY = "Resend API Key"