\n\n-- Drop existing policies\nDROP POLICY IF EXISTS "Users can insert their own profile" ON profiles;
\nDROP POLICY IF EXISTS "Users can update own profile" ON profiles;
\nDROP POLICY IF EXISTS "Users can update their own profile" ON profiles;
\nDROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON profiles;
\nDROP POLICY IF EXISTS "Profiles are viewable by authenticated users" ON profiles;
\n\n-- Ensure RLS is enabled\nALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
\n\n-- Create new policies\nCREATE POLICY "Profiles are viewable by authenticated users"\n  ON profiles\n  FOR SELECT\n  TO authenticated\n  USING (true);
\n\nCREATE POLICY "Users can insert their own profile"\n  ON profiles\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = id);
\n\nCREATE POLICY "Users can update own profile"\n  ON profiles\n  FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = id);
\n\n-- Ensure indexes exist\nCREATE INDEX IF NOT EXISTS profiles_username_idx ON profiles (username);
\nCREATE INDEX IF NOT EXISTS profiles_email_idx ON profiles (email);
\n\n-- Recreate public profiles view\nDROP VIEW IF EXISTS public_profiles;
\nCREATE VIEW public_profiles AS\n  SELECT id, username, avatar_url\n  FROM profiles;
\n\n-- Grant access to public profiles view\nGRANT SELECT ON public_profiles TO anon, authenticated;
;
