\n\n-- Add type and service_details columns to items table\nALTER TABLE items \nADD COLUMN IF NOT EXISTS type TEXT CHECK (type IN ('item', 'service')) DEFAULT 'item',\nADD COLUMN IF NOT EXISTS service_details JSONB;
\n\n-- Create index for type column\nCREATE INDEX IF NOT EXISTS idx_items_type ON items(type);
\n\n-- Update existing policies to handle service listings\nDROP POLICY IF EXISTS "Anyone can view active items" ON items;
\nCREATE POLICY "Anyone can view active listings"\n  ON items\n  FOR SELECT\n  USING (status = 'active');
\n\n-- Create function to validate service details\nCREATE OR REPLACE FUNCTION validate_service_details()\nRETURNS TRIGGER AS $$\nBEGIN\n  -- Only validate if this is a service type item\n  IF NEW.type = 'service' THEN\n    -- Check if service_details is present and has required fields\n    IF NEW.service_details IS NULL OR \n       NOT (NEW.service_details ? 'rateType' AND \n            NEW.service_details ? 'availability' AND\n            NEW.service_details ? 'remote') THEN\n      RAISE EXCEPTION 'Service listings must include rate type, availability, and remote work status';
\n    END IF;
\n    \n    -- Validate rate type\n    IF NOT (NEW.service_details->>'rateType' IN ('hourly', 'fixed', 'project')) THEN\n      RAISE EXCEPTION 'Invalid rate type for service';
\n    END IF;
\n  END IF;
\n  \n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql;
\n\n-- Create trigger for service validation\nDROP TRIGGER IF EXISTS validate_service_trigger ON items;
\nCREATE TRIGGER validate_service_trigger\n  BEFORE INSERT OR UPDATE ON items\n  FOR EACH ROW\n  EXECUTE FUNCTION validate_service_details();
\n\n-- Add service-specific notification types by modifying the type column\nALTER TABLE notifications \nALTER COLUMN type TYPE TEXT;
\n\n-- Add check constraint for notification types\nALTER TABLE notifications \nADD CONSTRAINT valid_notification_types \nCHECK (\n  type IN (\n    'success', 'error', 'info', 'warning',\n    'bid_received', 'bid_accepted', 'bid_rejected',\n    'payment_received', 'shipping_update', 'item_sold',\n    'email_verification', 'onboarding_reminder',\n    'service_booked', 'service_completed'\n  )\n);
\n\n-- Create index on notification type\nCREATE INDEX IF NOT EXISTS idx_notifications_type ON notifications(type);
;
