\n\n-- Function to check if email or username exists\nCREATE OR REPLACE FUNCTION check_user_exists(\n  check_email TEXT,\n  check_username TEXT\n) RETURNS TABLE (\n  exists_email BOOLEAN,\n  exists_username BOOLEAN\n) AS $$\nBEGIN\n  RETURN QUERY\n  SELECT \n    EXISTS(SELECT 1 FROM profiles WHERE email = check_email) as exists_email,\n    EXISTS(SELECT 1 FROM profiles WHERE username = check_username) as exists_username;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Function to clean up orphaned profiles\nCREATE OR REPLACE FUNCTION cleanup_orphaned_profiles()\nRETURNS void AS $$\nBEGIN\n  -- Delete profiles that don't have corresponding auth.users entries\n  DELETE FROM profiles p\n  WHERE NOT EXISTS (\n    SELECT 1 FROM auth.users u \n    WHERE u.id = p.id\n  );
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Run initial cleanup\nSELECT cleanup_orphaned_profiles();
\n\n-- Add trigger to automatically clean up orphaned profiles\nDROP TRIGGER IF EXISTS cleanup_profiles_trigger ON auth.users;
\n\nCREATE TRIGGER cleanup_profiles_trigger\nAFTER DELETE ON auth.users\nFOR EACH ROW\nEXECUTE FUNCTION cleanup_profile_on_user_delete();
;
