-- Remove the problematic constraint if it exists\nALTER TABLE profiles \nDROP CONSTRAINT IF EXISTS profiles_email_match_auth;
\n\n-- Create a function to validate email matches\nCREATE OR REPLACE FUNCTION validate_profile_email()\nRETURNS TRIGGER AS $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM auth.users \n    WHERE id = NEW.id AND email = NEW.email\n  ) THEN\n    RAISE EXCEPTION 'Profile email must match auth.users email';
\n  END IF;
\n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Add trigger to validate email on insert/update\nDROP TRIGGER IF EXISTS validate_profile_email_trigger ON profiles;
\nCREATE TRIGGER validate_profile_email_trigger\nBEFORE INSERT OR UPDATE OF email ON profiles\nFOR EACH ROW\nEXECUTE FUNCTION validate_profile_email();
\n\n-- Run cleanup one more time\nSELECT cleanup_orphaned_profiles();
;
