-- Clean up orphaned profiles\nCREATE OR REPLACE FUNCTION cleanup_orphaned_profiles()\nRETURNS void AS $$\nBEGIN\n  -- Delete profiles that don't have corresponding auth.users entries\n  DELETE FROM profiles\n  WHERE id NOT IN (\n    SELECT id FROM auth.users\n  );
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Run the cleanup\nSELECT cleanup_orphaned_profiles();
\n\n-- Create trigger to automatically clean up orphaned profiles\nCREATE OR REPLACE FUNCTION cleanup_profile_on_user_delete()\nRETURNS TRIGGER AS $$\nBEGIN\n  DELETE FROM profiles WHERE id = OLD.id;
\n  RETURN OLD;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\nCREATE TRIGGER cleanup_profile_trigger\n  AFTER DELETE ON auth.users\n  FOR EACH ROW\n  EXECUTE FUNCTION cleanup_profile_on_user_delete();
;
