-- Drop existing policies\nDROP POLICY IF EXISTS "Users can insert their own profile" ON profiles;
\nDROP POLICY IF EXISTS "Users can update own profile" ON profiles;
\nDROP POLICY IF EXISTS "Profiles are viewable by authenticated users" ON profiles;
\n\n-- Ensure RLS is enabled\nALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
\n\n-- Create new policies with proper permissions\nCREATE POLICY "Enable read access for authenticated users"\n  ON profiles\n  FOR SELECT\n  TO authenticated\n  USING (true);
\n\nCREATE POLICY "Enable insert for authenticated users"\n  ON profiles\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = id);
\n\nCREATE POLICY "Enable update for users based on id"\n  ON profiles\n  FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = id)\n  WITH CHECK (auth.uid() = id);
\n\n-- Grant necessary permissions\nGRANT ALL ON profiles TO authenticated;
\nGRANT ALL ON profiles TO service_role;
\n\n-- Create index for better query performance\nCREATE INDEX IF NOT EXISTS profiles_id_idx ON profiles(id);
;
