-- Drop all existing policies first\nDROP POLICY IF EXISTS "Profiles are viewable by authenticated users" ON profiles;
\nDROP POLICY IF EXISTS "Enable read access for authenticated users" ON profiles;
\nDROP POLICY IF EXISTS "Enable insert for authenticated users" ON profiles;
\nDROP POLICY IF EXISTS "Enable update for users based on id" ON profiles;
\nDROP POLICY IF EXISTS "Users can insert their own profile" ON profiles;
\nDROP POLICY IF EXISTS "Users can update own profile" ON profiles;
\nDROP POLICY IF EXISTS "Admins can view all profiles" ON profiles;
\nDROP POLICY IF EXISTS "Allow read access for authenticated users" ON profiles;
\nDROP POLICY IF EXISTS "Allow users to create their own profile" ON profiles;
\nDROP POLICY IF EXISTS "Allow users to update their own profile" ON profiles;
\n\n-- Ensure RLS is enabled\nALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
\n\n-- Create new simplified policies with unique names\nCREATE POLICY "profiles_read_policy"\n  ON profiles\n  FOR SELECT\n  TO authenticated\n  USING (true);
\n\nCREATE POLICY "profiles_insert_policy"\n  ON profiles\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = id);
\n\nCREATE POLICY "profiles_update_policy"\n  ON profiles\n  FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = id)\n  WITH CHECK (auth.uid() = id);
\n\n-- Create indexes for better performance\nCREATE INDEX IF NOT EXISTS idx_profiles_id ON profiles(id);
\nCREATE INDEX IF NOT EXISTS idx_profiles_email ON profiles(email);
\nCREATE INDEX IF NOT EXISTS idx_profiles_username ON profiles(username);
;
