-- Add onboarding fields to profiles table\nALTER TABLE profiles\nADD COLUMN IF NOT EXISTS shipping_address JSONB,\nADD COLUMN IF NOT EXISTS payment_setup BOOLEAN DEFAULT false,\nADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN DEFAULT false;
\n\n-- Create index for onboarding status\nCREATE INDEX IF NOT EXISTS idx_profiles_onboarding_completed ON profiles(onboarding_completed);
\n\n-- Create function to check onboarding status\nCREATE OR REPLACE FUNCTION check_onboarding_status(user_id UUID)\nRETURNS BOOLEAN AS $$\nBEGIN\n  RETURN EXISTS (\n    SELECT 1 FROM profiles\n    WHERE id = user_id\n    AND shipping_address IS NOT NULL\n    AND payment_setup = true\n    AND onboarding_completed = true\n  );
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Add RLS policy for onboarding fields\nCREATE POLICY "Users can update their own onboarding status"\n  ON profiles\n  FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = id)\n  WITH CHECK (auth.uid() = id);
\n\n-- Create function to complete onboarding\nCREATE OR REPLACE FUNCTION complete_onboarding(user_id UUID)\nRETURNS BOOLEAN AS $$\nBEGIN\n  UPDATE profiles\n  SET onboarding_completed = true\n  WHERE id = user_id;
\n  \n  RETURN FOUND;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Add notification for incomplete onboarding\nCREATE OR REPLACE FUNCTION notify_incomplete_onboarding()\nRETURNS TRIGGER AS $$\nBEGIN\n  IF NEW.onboarding_completed = false THEN\n    INSERT INTO notifications (\n      user_id,\n      type,\n      message,\n      data\n    ) VALUES (\n      NEW.id,\n      'onboarding_reminder',\n      'Complete your profile setup to start using all features',\n      jsonb_build_object(\n        'onboarding_step', \n        CASE \n          WHEN NEW.shipping_address IS NULL THEN 'address'\n          WHEN NEW.payment_setup = false THEN 'payment'\n          ELSE 'incomplete'\n        END\n      )\n    );
\n  END IF;
\n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Create trigger for incomplete onboarding notifications\nDROP TRIGGER IF EXISTS notify_incomplete_onboarding_trigger ON profiles;
\nCREATE TRIGGER notify_incomplete_onboarding_trigger\n  AFTER INSERT ON profiles\n  FOR EACH ROW\n  EXECUTE FUNCTION notify_incomplete_onboarding();
;
