-- Create email templates table\nCREATE TABLE IF NOT EXISTS email_templates (\n  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  name TEXT NOT NULL UNIQUE,\n  subject TEXT NOT NULL,\n  html_content TEXT NOT NULL,\n  created_at TIMESTAMPTZ DEFAULT now()\n);
\n\n-- Insert default email templates\nINSERT INTO email_templates (name, subject, html_content) VALUES\n('verify_email', 'Verify your VersoBid email address', '\n<!DOCTYPE html>\n<html>\n<head>\n  <style>\n    body { font-family: Arial, sans-serif;
 line-height: 1.6;
 }\n    .container { max-width: 600px;
 margin: 0 auto;
 padding: 20px;
 }\n    .header { background-color: #4F46E5;
 color: white;
 padding: 20px;
 text-align: center;
 }\n    .content { padding: 20px;
 }\n    .button { \n      display: inline-block;
\n      padding: 12px 24px;
\n      background-color: #4F46E5;
\n      color: white;
\n      text-decoration: none;
\n      border-radius: 4px;
\n      margin: 20px 0;
\n    }\n  </style>\n</head>\n<body>\n  <div class="container">\n    <div class="header">\n      <h1>Welcome to VersoBid!</h1>\n    </div>\n    <div class="content">\n      <h2>Verify Your Email Address</h2>\n      <p>Thanks for signing up! Please click the button below to verify your email address:</p>\n      <a href="{{verification_link}}" class="button">Verify Email</a>\n      <p>If you did not create an account, you can safely ignore this email.</p>\n    </div>\n  </div>\n</body>\n</html>\n'),\n('welcome', 'Welcome to VersoBid - Email Verified!', '\n<!DOCTYPE html>\n<html>\n<head>\n  <style>\n    body { font-family: Arial, sans-serif;
 line-height: 1.6;
 }\n    .container { max-width: 600px;
 margin: 0 auto;
 padding: 20px;
 }\n    .header { background-color: #4F46E5;
 color: white;
 padding: 20px;
 text-align: center;
 }\n    .content { padding: 20px;
 }\n    .button { \n      display: inline-block;
\n      padding: 12px 24px;
\n      background-color: #4F46E5;
\n      color: white;
\n      text-decoration: none;
\n      border-radius: 4px;
\n      margin: 20px 0;
\n    }\n  </style>\n</head>\n<body>\n  <div class="container">\n    <div class="header">\n      <h1>Email Verified!</h1>\n    </div>\n    <div class="content">\n      <h2>Welcome to VersoBid</h2>\n      <p>Your email has been verified successfully. You can now start using all features of VersoBid!</p>\n      <p>Get started by completing your profile and exploring items:</p>\n      <a href="{{dashboard_link}}" class="button">Go to Dashboard</a>\n    </div>\n  </div>\n</body>\n</html>\n');
\n\n-- Create function to send verification email\nCREATE OR REPLACE FUNCTION send_verification_email()\nRETURNS TRIGGER AS $$\nBEGIN\n  -- Log the email sending attempt\n  INSERT INTO email_logs (\n    recipient,\n    subject,\n    template_name,\n    status\n  ) VALUES (\n    NEW.email,\n    'Verify your VersoBid email address',\n    'verify_email',\n    'pending'\n  );
\n\n  -- Create notification\n  INSERT INTO notifications (\n    user_id,\n    type,\n    message,\n    data\n  ) VALUES (\n    NEW.id,\n    'email_verification',\n    'Please verify your email address',\n    jsonb_build_object(\n      'email', NEW.email,\n      'verification_link', format('%s/verify-email?token=%s', \n        current_setting('app.frontend_url', true),\n        encode(gen_random_bytes(32), 'base64')\n      )\n    )\n  );
\n\n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Create function to handle email verification\nCREATE OR REPLACE FUNCTION handle_email_verification()\nRETURNS TRIGGER AS $$\nBEGIN\n  IF NEW.email_confirmed_at IS NOT NULL AND OLD.email_confirmed_at IS NULL THEN\n    -- Log welcome email\n    INSERT INTO email_logs (\n      recipient,\n      subject,\n      template_name,\n      status\n    ) VALUES (\n      NEW.email,\n      'Welcome to VersoBid - Email Verified!',\n      'welcome',\n      'pending'\n    );
\n\n    -- Create welcome notification\n    INSERT INTO notifications (\n      user_id,\n      type,\n      message,\n      data\n    ) VALUES (\n      NEW.id,\n      'welcome',\n      'Welcome to VersoBid! Your email has been verified.',\n      jsonb_build_object(\n        'email', NEW.email,\n        'verified_at', NEW.email_confirmed_at\n      )\n    );
\n  END IF;
\n\n  RETURN NEW;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
\n\n-- Create triggers\nDROP TRIGGER IF EXISTS send_verification_email_trigger ON auth.users;
\nCREATE TRIGGER send_verification_email_trigger\n  AFTER INSERT ON auth.users\n  FOR EACH ROW\n  EXECUTE FUNCTION send_verification_email();
\n\nDROP TRIGGER IF EXISTS handle_email_verification_trigger ON auth.users;
\nCREATE TRIGGER handle_email_verification_trigger\n  AFTER UPDATE OF email_confirmed_at ON auth.users\n  FOR EACH ROW\n  EXECUTE FUNCTION handle_email_verification();
\n\n-- Update RLS policies\nALTER TABLE email_templates ENABLE ROW LEVEL SECURITY;
\n\nCREATE POLICY "Public can view email templates"\n  ON email_templates\n  FOR SELECT\n  TO public\n  USING (true);
;
