\n\n-- Create listings table\nCREATE TABLE IF NOT EXISTS listings (\n  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  title TEXT NOT NULL,\n  description TEXT,\n  price NUMERIC NOT NULL CHECK (price >= 0),\n  seller_id UUID REFERENCES profiles(id) NOT NULL,\n  category TEXT NOT NULL,\n  status TEXT NOT NULL DEFAULT 'active',\n  created_at TIMESTAMPTZ DEFAULT now(),\n  CHECK (status IN ('active', 'sold', 'archived'))\n);
\n\n-- Create bids table\nCREATE TABLE IF NOT EXISTS bids (\n  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n  listing_id UUID REFERENCES listings(id) NOT NULL,\n  bidder_id UUID REFERENCES profiles(id) NOT NULL,\n  amount NUMERIC NOT NULL CHECK (amount >= 0),\n  status TEXT NOT NULL DEFAULT 'pending',\n  created_at TIMESTAMPTZ DEFAULT now(),\n  CHECK (status IN ('pending', 'accepted', 'rejected'))\n);
\n\n-- Enable RLS\nALTER TABLE listings ENABLE ROW LEVEL SECURITY;
\nALTER TABLE bids ENABLE ROW LEVEL SECURITY;
\n\n-- Listings policies\nCREATE POLICY "Anyone can view active listings"\n  ON listings\n  FOR SELECT\n  USING (status = 'active');
\n\nCREATE POLICY "Users can create their own listings"\n  ON listings\n  FOR INSERT\n  WITH CHECK (auth.uid() = seller_id);
\n\nCREATE POLICY "Sellers can update their own listings"\n  ON listings\n  FOR UPDATE\n  USING (auth.uid() = seller_id);
\n\n-- Bids policies\nCREATE POLICY "Users can view their own bids"\n  ON bids\n  FOR SELECT\n  USING (auth.uid() = bidder_id);
\n\nCREATE POLICY "Sellers can view bids on their listings"\n  ON bids\n  FOR SELECT\n  USING (EXISTS (\n    SELECT 1 FROM listings\n    WHERE listings.id = bids.listing_id\n    AND listings.seller_id = auth.uid()\n  ));
\n\nCREATE POLICY "Users can create bids"\n  ON bids\n  FOR INSERT\n  WITH CHECK (auth.uid() = bidder_id);
\n\nCREATE POLICY "Users can update their own bids"\n  ON bids\n  FOR UPDATE\n  USING (auth.uid() = bidder_id);
\n\n-- Create indexes\nCREATE INDEX listings_seller_id_idx ON listings(seller_id);
\nCREATE INDEX listings_category_idx ON listings(category);
\nCREATE INDEX listings_status_idx ON listings(status);
\nCREATE INDEX bids_listing_id_idx ON bids(listing_id);
\nCREATE INDEX bids_bidder_id_idx ON bids(bidder_id);
;
