\n\n-- Update welcome email template\nUPDATE email_templates \nSET html_content = '\n<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <meta http-equiv="X-UA-Compatible" content="IE=edge">\n    <title>Welcome to VersoBid - Verify Your Email</title>\n    <!--[if mso]>\n    <style type="text/css">\n    .fallback-font {\n        font-family: Arial, sans-serif;
\n    }\n    </style>\n    <![endif]-->\n    <style>\n        /* Reset styles */\n        body, #bodyTable, #bodyCell {\n            height: 100% !important;
\n            margin: 0;
\n            padding: 0;
\n            width: 100% !important;
\n        }\n        \n        body {\n            -webkit-text-size-adjust: 100%;
\n            -ms-text-size-adjust: 100%;
\n            margin: 0;
\n            padding: 0;
\n            -webkit-font-smoothing: antialiased;
\n            font-family: ''Segoe UI'', system-ui, -apple-system, sans-serif;
\n        }\n        \n        table {\n            border-collapse: collapse;
\n        }\n        \n        img, a img {\n            border: 0;
\n            height: auto;
\n            outline: none;
\n            text-decoration: none;
\n        }\n        \n        /* Base styles */\n        .container {\n            max-width: 600px;
\n            margin: 0 auto;
\n            background-color: #ffffff;
\n            padding: 40px 20px;
\n        }\n        \n        .header {\n            background-color: #4F46E5;
\n            padding: 40px 20px;
\n            text-align: center;
\n            border-radius: 8px 8px 0 0;
\n        }\n        \n        .content {\n            padding: 40px 20px;
\n            background-color: #ffffff;
\n            border-radius: 0 0 8px 8px;
\n            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
\n        }\n        \n        .button {\n            display: inline-block;
\n            padding: 14px 32px;
\n            background-color: #4F46E5;
\n            color: #ffffff;
\n            text-decoration: none;
\n            border-radius: 6px;
\n            font-weight: 600;
\n            margin: 20px 0;
\n            text-align: center;
\n            transition: background-color 0.2s;
\n        }\n        \n        .button:hover {\n            background-color: #4338CA;
\n        }\n        \n        .footer {\n            margin-top: 40px;
\n            text-align: center;
\n            color: #6B7280;
\n            font-size: 14px;
\n        }\n        \n        /* Responsive styles */\n        @media screen and (max-width: 600px) {\n            .container {\n                width: 100% !important;
\n                padding: 20px 10px;
\n            }\n            \n            .header {\n                padding: 30px 15px;
\n            }\n            \n            .content {\n                padding: 30px 15px;
\n            }\n            \n            .button {\n                display: block;
\n                margin: 20px auto;
\n                text-align: center;
\n                width: 80%;
\n            }\n        }\n    </style>\n</head>\n<body>\n    <table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="100%" class="container">\n        <tr>\n            <td>\n                <div class="header">\n                    <h1 style="color: #ffffff;
 margin: 0;
 font-size: 28px;
 font-weight: 700;
">Welcome to VersoBid!</h1>\n                </div>\n                \n                <div class="content">\n                    <h2 style="color: #1F2937;
 margin-top: 0;
">Hi {{params.name}},</h2>\n                    \n                    <p style="color: #4B5563;
 font-size: 16px;
 line-height: 1.6;
">\n                        Thank you for joining VersoBid! To get started, please verify your email address by clicking the button below:\n                    </p>\n                    \n                    <a href="{{params.verification_link}}" class="button">\n                        Verify Email Address\n                    </a>\n                    \n                    <p style="color: #4B5563;
 font-size: 16px;
 line-height: 1.6;
">\n                        Once verified, you''ll have access to all VersoBid features:\n                    </p>\n                    \n                    <ul style="color: #4B5563;
 font-size: 16px;
 line-height: 1.6;
">\n                        <li>Post items you want to buy</li>\n                        <li>Receive competitive bids from sellers</li>\n                        <li>Make secure payments through our platform</li>\n                        <li>Track your transactions and shipping</li>\n                    </ul>\n                    \n                    <p style="color: #4B5563;
 font-size: 16px;
 line-height: 1.6;
">\n                        If you didn''t create an account with VersoBid, you can safely ignore this email.\n                    </p>\n                    \n                    <div style="margin: 40px 0;
 padding: 20px;
 background-color: #F3F4F6;
 border-radius: 6px;
">\n                        <p style="color: #4B5563;
 font-size: 14px;
 margin: 0;
">\n                            Button not working? Copy and paste this link into your browser:\n                            <br>\n                            <a href="{{params.verification_link}}" style="color: #4F46E5;
 word-break: break-all;
">\n                                {{params.verification_link}}\n                            </a>\n                        </p>\n                    </div>\n                    \n                    <div class="footer">\n                        <p style="margin-bottom: 10px;
">\n                            Need help? Contact our support team at \n                            <a href="mailto:support@versobid.com" style="color: #4F46E5;
">support@versobid.com</a>\n                        </p>\n                        <p style="margin: 0;
">\n                            © {{params.current_year}} VersoBid. All rights reserved.\n                        </p>\n                    </div>\n                </div>\n            </td>\n        </tr>\n    </table>\n</body>\n</html>\n'\nWHERE name = 'welcome';
\n\n-- If the template doesn't exist, insert it\nINSERT INTO email_templates (name, subject, html_content)\nSELECT 'welcome', 'Welcome to VersoBid - Verify Your Email', html_content\nFROM (\n  SELECT html_content FROM email_templates WHERE name = 'welcome' LIMIT 1\n) AS subquery\nWHERE NOT EXISTS (\n  SELECT 1 FROM email_templates WHERE name = 'welcome'\n);
;
