\n\n-- Insert or update welcome email template\nINSERT INTO email_templates (name, subject, html_content) VALUES\n('versobid_welcomeEmail', 'Welcome to VersoBid!', '\n<!DOCTYPE html>\n<html>\n<head>\n  <style>\n    body { font-family: Arial, sans-serif;
 line-height: 1.6;
 }\n    .container { max-width: 600px;
 margin: 0 auto;
 padding: 20px;
 }\n    .header { background-color: #4F46E5;
 color: white;
 padding: 20px;
 text-align: center;
 }\n    .content { padding: 20px;
 }\n    .button {\n      display: inline-block;
\n      padding: 12px 24px;
\n      background-color: #4F46E5;
\n      color: white;
\n      text-decoration: none;
\n      border-radius: 4px;
\n      margin: 20px 0;
\n    }\n  </style>\n</head>\n<body>\n  <div class="container">\n    <div class="header">\n      <h1>Welcome to VersoBid!</h1>\n    </div>\n    <div class="content">\n      <h2>Hi {{params.to_name}},</h2>\n      <p>Thank you for joining VersoBid! We''re excited to have you as part of our community.</p>\n      <p>With VersoBid, you can:</p>\n      <ul>\n        <li>Post items you want to buy</li>\n        <li>Receive competitive bids from sellers</li>\n        <li>Make secure payments through our platform</li>\n      </ul>\n      <a href="{{params.login_url}}" class="button">Get Started</a>\n      <p>If you have any questions, feel free to reach out to our support team at {{params.support_email}}.</p>\n      <p>Best regards,<br>The VersoBid Team</p>\n      <p style="color: #666;
 font-size: 12px;
 margin-top: 20px;
">\n        © {{params.current_year}} VersoBid. All rights reserved.\n      </p>\n    </div>\n  </div>\n</body>\n</html>\n') ON CONFLICT (name) DO UPDATE \nSET subject = EXCLUDED.subject,\n    html_content = EXCLUDED.html_content;
\n\n-- Insert or update bid notification template\nINSERT INTO email_templates (name, subject, html_content) VALUES\n('versobid_bidEmail', 'New Bid Received on Your Item', '\n<!DOCTYPE html>\n<html>\n<head>\n  <style>\n    body { font-family: Arial, sans-serif;
 line-height: 1.6;
 }\n    .container { max-width: 600px;
 margin: 0 auto;
 padding: 20px;
 }\n    .header { background-color: #4F46E5;
 color: white;
 padding: 20px;
 text-align: center;
 }\n    .content { padding: 20px;
 }\n    .button {\n      display: inline-block;
\n      padding: 12px 24px;
\n      background-color: #4F46E5;
\n      color: white;
\n      text-decoration: none;
\n      border-radius: 4px;
\n      margin: 20px 0;
\n    }\n    .bid-details {\n      background-color: #f8fafc;
\n      border-radius: 8px;
\n      padding: 20px;
\n      margin: 20px 0;
\n    }\n  </style>\n</head>\n<body>\n  <div class="container">\n    <div class="header">\n      <h1>New Bid Received!</h1>\n    </div>\n    <div class="content">\n      <h2>Hi {{params.to_name}},</h2>\n      <p>You''ve received a new bid on your item.</p>\n      \n      <div class="bid-details">\n        <p><strong>Message:</strong> {{params.message}}</p>\n        <p><strong>Item Link:</strong> <a href="{{params.item_link}}">View Item</a></p>\n      </div>\n\n      <a href="{{params.item_link}}" class="button">View Bid Details</a>\n      \n      <p>Best regards,<br>The VersoBid Team</p>\n      <p style="color: #666;
 font-size: 12px;
 margin-top: 20px;
">\n        © {{params.current_year}} VersoBid. All rights reserved.\n      </p>\n    </div>\n  </div>\n</body>\n</html>\n') ON CONFLICT (name) DO UPDATE \nSET subject = EXCLUDED.subject,\n    html_content = EXCLUDED.html_content;
\n\n-- Insert or update bid accepted template\nINSERT INTO email_templates (name, subject, html_content) VALUES\n('versobid_bidAccepted', 'Your Bid Has Been Accepted!', '\n<!DOCTYPE html>\n<html>\n<head>\n  <style>\n    body { font-family: Arial, sans-serif;
 line-height: 1.6;
 }\n    .container { max-width: 600px;
 margin: 0 auto;
 padding: 20px;
 }\n    .header { background-color: #4F46E5;
 color: white;
 padding: 20px;
 text-align: center;
 }\n    .content { padding: 20px;
 }\n    .button {\n      display: inline-block;
\n      padding: 12px 24px;
\n      background-color: #4F46E5;
\n      color: white;
\n      text-decoration: none;
\n      border-radius: 4px;
\n      margin: 20px 0;
\n    }\n    .success-message {\n      background-color: #ecfdf5;
\n      border-radius: 8px;
\n      padding: 20px;
\n      margin: 20px 0;
\n      border-left: 4px solid #10b981;
\n    }\n  </style>\n</head>\n<body>\n  <div class="container">\n    <div class="header">\n      <h1>Congratulations!</h1>\n    </div>\n    <div class="content">\n      <div class="success-message">\n        <h2>Your bid has been accepted!</h2>\n        <p>{{params.message}}</p>\n      </div>\n\n      <p>To complete the purchase, please click the button below:</p>\n      <a href="{{params.payment_link}}" class="button">Complete Payment</a>\n\n      <p>If you have any questions, please don''t hesitate to contact us.</p>\n      \n      <p>Best regards,<br>The VersoBid Team</p>\n      <p style="color: #666;
 font-size: 12px;
 margin-top: 20px;
">\n        © {{params.current_year}} VersoBid. All rights reserved.\n      </p>\n    </div>\n  </div>\n</body>\n</html>\n') ON CONFLICT (name) DO UPDATE \nSET subject = EXCLUDED.subject,\n    html_content = EXCLUDED.html_content;
;
