\n\nDO $$ \nBEGIN\n  -- First delete any admin activity logs for the test account\n  DELETE FROM public.admin_activity_log\n  WHERE admin_id IN (\n    SELECT id FROM public.profiles WHERE email = 'test@example.com'\n  );
\n\n  -- Delete any email logs for the test account\n  DELETE FROM public.email_logs \n  WHERE recipient = 'test@example.com';
\n\n  -- Then delete any existing profile for the test account\n  DELETE FROM public.profiles \n  WHERE email = 'test@example.com';
\n\n  -- Then delete any existing user account\n  DELETE FROM auth.users \n  WHERE email = 'test@example.com';
\n\n  -- Small delay to ensure deletion is complete\n  PERFORM pg_sleep(0.5);
\n\n  -- Temporarily disable email verification trigger\n  ALTER TABLE auth.users DISABLE TRIGGER send_verification_email_trigger;
\n  ALTER TABLE public.profiles DISABLE TRIGGER send_welcome_email_trigger;
\n\n  -- Create new test user account\n  INSERT INTO auth.users (\n    instance_id,\n    id,\n    aud,\n    role,\n    email,\n    encrypted_password,\n    email_confirmed_at,\n    recovery_sent_at,\n    last_sign_in_at,\n    raw_app_meta_data,\n    raw_user_meta_data,\n    created_at,\n    updated_at,\n    confirmation_token,\n    email_change,\n    email_change_token_new,\n    recovery_token\n  ) VALUES (\n    '00000000-0000-0000-0000-000000000000',\n    '00000000-0000-0000-0000-000000000001',\n    'authenticated',\n    'authenticated',\n    'test@example.com',\n    crypt('Hellworld1!', gen_salt('bf')),\n    NOW(),\n    NOW(),\n    NOW(),\n    '{"provider":"email","providers":["email"]}',\n    '{"username":"testuser","full_name":"Test User"}',\n    NOW(),\n    NOW(),\n    '',\n    '',\n    '',\n    ''\n  );
\n\n  -- Create corresponding profile\n  INSERT INTO public.profiles (\n    id,\n    email,\n    username,\n    full_name,\n    avatar_url,\n    email_verified,\n    is_admin,\n    created_at\n  ) VALUES (\n    '00000000-0000-0000-0000-000000000001',\n    'test@example.com',\n    'testuser',\n    'Test User',\n    NULL,\n    true,\n    false,\n    NOW()\n  );
\n\n  -- Re-enable email verification trigger\n  ALTER TABLE auth.users ENABLE TRIGGER send_verification_email_trigger;
\n  ALTER TABLE public.profiles ENABLE TRIGGER send_welcome_email_trigger;
\n\nEXCEPTION WHEN OTHERS THEN\n  -- Re-enable triggers even if there's an error\n  ALTER TABLE auth.users ENABLE TRIGGER send_verification_email_trigger;
\n  ALTER TABLE public.profiles ENABLE TRIGGER send_welcome_email_trigger;
\n  \n  -- Log error details\n  RAISE NOTICE 'Error creating test account: %', SQLERRM;
\n  -- Re-raise the error\n  RAISE;
\nEND $$;
;
