-- Create storage bucket for avatars\nINSERT INTO storage.buckets (id, name, public)\nVALUES ('avatars', 'avatars', true);
\n\n-- Create storage policy to allow authenticated users to upload their own avatar\nCREATE POLICY "Users can upload their own avatar"\nON storage.objects\nFOR INSERT\nTO authenticated\nWITH CHECK (\n  bucket_id = 'avatars' AND\n  (storage.foldername(name))[1] = auth.uid()::text\n);
\n\n-- Allow users to update their own avatar\nCREATE POLICY "Users can update their own avatar"\nON storage.objects\nFOR UPDATE\nTO authenticated\nUSING (\n  bucket_id = 'avatars' AND\n  (storage.foldername(name))[1] = auth.uid()::text\n);
\n\n-- Allow public access to avatars\nCREATE POLICY "Public can view avatars"\nON storage.objects\nFOR SELECT\nTO public\nUSING (bucket_id = 'avatars');
\n\n-- Add avatar_url column to profiles if not exists\nDO $$ \nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns \n    WHERE table_name = 'profiles' \n    AND column_name = 'avatar_url'\n  ) THEN\n    ALTER TABLE profiles ADD COLUMN avatar_url TEXT;
\n  END IF;
\nEND $$;
\n\n-- Add rating column to profiles if not exists\nDO $$ \nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns \n    WHERE table_name = 'profiles' \n    AND column_name = 'rating'\n  ) THEN\n    ALTER TABLE profiles ADD COLUMN rating NUMERIC DEFAULT 0;
\n  END IF;
\nEND $$;
;
