-- Function to safely delete a user and their associated data\nCREATE OR REPLACE FUNCTION delete_user_by_email(admin_user_id UUID, target_email TEXT)\nRETURNS BOOLEAN AS $$\nDECLARE\n  target_user_id UUID;
\nBEGIN\n  -- Check if the requesting user is an admin\n  IF NOT is_admin(admin_user_id) THEN\n    RAISE EXCEPTION 'Unauthorized: Only admins can delete users';
\n  END IF;
\n\n  -- Get the user ID for the target email\n  SELECT id INTO target_user_id\n  FROM auth.users\n  WHERE email = target_email;
\n\n  IF target_user_id IS NULL THEN\n    RAISE EXCEPTION 'User not found with email: %', target_email;
\n  END IF;
\n\n  -- Delete profile first (this will cascade to related data)\n  DELETE FROM profiles WHERE id = target_user_id;
\n  \n  -- Delete the auth user\n  DELETE FROM auth.users WHERE id = target_user_id;
\n\n  -- Log the admin action\n  PERFORM log_admin_activity(\n    admin_user_id,\n    'delete_user',\n    'user',\n    target_user_id,\n    jsonb_build_object('email', target_email)\n  );
\n\n  RETURN TRUE;
\nEND;
\n$$ LANGUAGE plpgsql SECURITY DEFINER;
;
