-- Drop existing policies\nDROP POLICY IF EXISTS "profiles_read_policy" ON profiles;
\nDROP POLICY IF EXISTS "profiles_insert_policy" ON profiles;
\nDROP POLICY IF EXISTS "profiles_update_policy" ON profiles;
\n\n-- Create new policies\nCREATE POLICY "allow_read_all_profiles"\n  ON profiles\n  FOR SELECT\n  TO authenticated\n  USING (true);
\n\nCREATE POLICY "allow_insert_own_profile"\n  ON profiles\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = id);
\n\nCREATE POLICY "allow_update_own_profile"\n  ON profiles\n  FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = id)\n  WITH CHECK (auth.uid() = id);
\n\n-- Ensure indexes exist\nCREATE INDEX IF NOT EXISTS idx_profiles_auth_id ON profiles(id);
\nCREATE INDEX IF NOT EXISTS idx_profiles_email ON profiles(email);
\nCREATE INDEX IF NOT EXISTS idx_profiles_username ON profiles(username);
;
