// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '../../types/supabase';


const SUPABASE_URL = "https://srefxubqmfxgkgzjncfr.supabase.co/";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyZWZ4dWJxbWZ4Z2tnempuY2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5MDk1OTksImV4cCI6MjA1MDQ4NTU5OX0.ZHzMMp8BP3NQbqlSDHK-KgNydp_BmViLVUCNL2sH6as";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);